"""待办事项仓储端口。"""
from __future__ import annotations

from typing import Dict, List, Optional, Protocol

from ai_todo_assistant.domain.models import Todo


class TodoRepository(Protocol):
    """应用层依赖的待办仓储协议，基础设施层负责提供具体实现。"""

    def add(
        self,
        title: str,
        description: str = "",
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        priority: str = "medium",
        due_date: Optional[str] = None,
    ) -> Todo: ...

    def delete(self, todo_id: str) -> bool: ...

    def update(
        self,
        todo_id: str,
        title: Optional[str] = None,
        description: Optional[str] = None,
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        priority: Optional[str] = None,
    ) -> Optional[Todo]: ...

    def toggle_completed(self, todo_id: str) -> Optional[Todo]: ...

    def get_by_id(self, todo_id: str) -> Optional[Todo]: ...

    def get_all(self) -> List[Todo]: ...

    def get_by_date(self, date: str) -> List[Todo]: ...

    def get_tasks_on_date(self, date_str: str) -> List[Todo]: ...

    def get_created_on(self, date: str) -> List[Todo]: ...

    def get_due_on(self, date: str) -> List[Todo]: ...

    def get_by_status(self, completed: bool) -> List[Todo]: ...

    def get_overdue(self) -> List[Todo]: ...

    def get_upcoming(self, days: int = 2) -> List[Todo]: ...

    def get_today(self) -> List[Todo]: ...

    def get_this_week(self) -> List[Todo]: ...

    def get_this_month(self) -> List[Todo]: ...

    def get_by_month(self, year: int, month: int) -> Dict[str, List[Todo]]: ...

    def search(self, keyword: str) -> List[Todo]: ...

    def get_by_priority(self, priority: str) -> List[Todo]: ...

    def get_statistics(self) -> dict: ...

    def clear_completed(self) -> int: ...

    def remember_preference(self, key: str, value: str) -> None: ...

    def list_preferences(self) -> Dict[str, str]: ...

    def forget_preference(self, key: str) -> bool: ...
