"""Workflow repository port."""
from __future__ import annotations

from typing import Protocol

from ai_todo_assistant.domain.workflow import Evidence, WorkItem


class WorkflowRepository(Protocol):
    def save_work_item(self, item: WorkItem) -> WorkItem: ...

    def get_work_item(self, work_item_id: str) -> WorkItem | None: ...

    def find_work_item_by_source(self, source: str, source_ref: str) -> WorkItem | None: ...

    def find_work_items_by_identity(self, identity: str) -> list[WorkItem]: ...

    def list_work_items(self, include_closed: bool = False) -> list[WorkItem]: ...

    def add_evidence(self, evidence: Evidence) -> Evidence: ...

    def list_evidence(self, work_item_id: str) -> list[Evidence]: ...

    def move_evidence(self, from_work_item_id: str, to_work_item_id: str) -> list[str]: ...

    def move_evidence_ids(self, evidence_ids: list[str], to_work_item_id: str) -> list[str]: ...
